# Generated by Django 5.0 on 2023-12-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hermano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fechaNacimiento", models.DateField()),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
