# Generated by Django 5.0 on 2023-12-12 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hermanos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hermano",
            new_name="Hermanos",
        ),
    ]
