# Generated by Django 5.0 on 2023-12-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hermanos", "0002_rename_hermano_hermanos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hermanos",
            name="nombre",
            field=models.CharField(max_length=20),
        ),
    ]
