# Generated by Django 5.0 on 2023-12-13 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hermanos", "0003_alter_hermanos_nombre"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hermanos",
            new_name="Hermano",
        ),
    ]
